---
title: Ajouter un effet de transparence
hero_image: images/banner.png
description: Ajoute un effet de transparence aux éléments HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter un effet de transparence
